config/routes.rb
Rails.application.routes.draw do
   

  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

   resources :links
   
   get 'link_index'=>'links#index'

   get "create_link" => 'links#new'
   post "create_link" => 'links#create'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

end

app/models/link.rb
class Link < ActiveRecord::Base
	validates :url, :format => URI::regexp(%w(http https))
	validates :url, :presence => true
	validates :title, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base

	def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
  	if logged_in?
  		redirect_to link_index_path
  	end
 end

 	  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

    # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	def show
		@link = Link.find(params[:id])
	end

	def new
		@link = Link.new
	end

    def index
    @links = Link.all
    end

    def create
        @link = Link.new(link_params)

      #  binding.pry
        begin
        	 @link.save!
        rescue Exception => e
        	#flash[:danger] = "#{e.message}"
        	flash.now[:alert] = "#{e.message}"
        	render :new
        	return
        end

         @link.save
         redirect_to(links_url)
    end

    def edit
    @link = Link.find(params[:id])
    end

    def update
    temp = Link.new(link_params)
    @link = Link.find(params[:id])

    @link.title = temp.title
    @link.url = temp.url
    begin
    	@link.save!
    rescue Exception => e
    	    flash.now[:alert] = "#{e.message}"
        	render :edit
    	 return
    end
    @link.save    
    temp.destroy

    flash[:notice] = "File updated"
    redirect_to links_url  
     end

    def destroy
    @link = Link.find(params[:id])
    @link.destroy
    flash[:notice] = "File deleted"
    redirect_to links_url    
    end

	def link_params
      params.require(:link).permit(:title, :url)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to link_index_path
  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper


end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Links</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class='alert alert-info fade in' data-alert='alert'>
    <div class="row">
  <div class="col-xs-13 col-sm-7 col-sm-offset-10">
  
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
   
    </div>
    </div>
	</div>
    <div class="container master-container">
    
    <div>
      <%= bootstrap_flash %>
    	<%= yield %>
    </div>
    
    </div>
</body>
</html>

app/views/layouts/link.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Links" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Links</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/links/edit.html.erb
  <%= form_for @link, html: { multipart: true } do |f| %>
    <br>
    <br>
         <div class="row">
         <div class="col-xs-12 col-sm-6 col-sm-offset-3">
         <label> Edit Link </label>
    <br>
    <br>
    <%= f.text_field :title %>
    <br>
    <div>
        
    <br>
    <%= f.text_field :url %>
    <br>

    </div>
    <br>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/links/index.html.erb
<table id="links" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>URL</th>
      <th colspan="3">Actions</th>         
    </tr>
  </thead>
  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.id %></td>
        <td><%= link.title %></td>
        <td><%= link.url %></td> 
        <td>
          <%= link_to "Show", links_path, class: "btn btn-primary btn-sm" %>
        </td>  
        <td>
          <%= link_to "Edit", links_url, method: :get, class: "btn btn-warning btn-sm" %>
        </td>       
        <td>
          <%= link_to "Delete", links_url, class: "btn btn-danger btn-sm"  %>          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Link', create_link_path, class: "btn btn-success"  %>

app/views/links/new.html.erb
<div class="panel panel-info">
<div class="panel-heading">Create New URL</div>
  <div class="panel-body">
<%= simple_form_for @link ,wrapper: :horizontal_form do |f| %>
  <%= f.input :title%>
  <%= f.input :url %>
  <%= f.button :submit , class: "my-button"%>
<% end %>
</div>
</div>